In [1]:
from sklearn.metrics import mean_absolute_error
from tensorflow.keras import models
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers.schedules import ExponentialDecay
from tensorflow.keras import regularizers
from tensorflow.keras.layers.experimental.preprocessing import Normalization
from sklearn import preprocessing
import numpy as np
import pandas as pd

2023-08-10 17:00:38.444085: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-10 17:00:38.445895: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-10 17:00:38.483636: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-10 17:00:38.485013: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-10 17:00:39.142039: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not fin

In [2]:
df = pd.read_csv('../raw_data/teste_argo_data.csv')
df.head()

x          y       15.0       20.0       25.0       30.0  \
0   51.582001 -45.755001   5.681237   5.683842   5.603836   5.518481   
1   92.547997 -43.222000  10.326000  10.326000  10.326000  10.326098   
2   89.600998 -56.223000   2.383455   2.381051   2.383966   2.386997   
3  115.977997 -45.905998   9.729325   9.714897   9.688203   9.658428   
4   64.942001 -50.344002   5.158442   5.158958   5.159000   5.159000   

        35.0       40.0       45.0       50.0  ...     935.0     940.0  \
0   5.438179   5.358996   5.299932   5.243129  ...  2.495287  2.492187   
1  10.328574  10.331011  10.331514  10.332000  ...  5.563226  5.486413   
2   2.388578   2.390099   2.391089   2.392000  ...  1.955992  1.952437   
3   9.637267   9.616872   9.606910   9.598658  ...  5.321880  5.270394   
4   5.159450   5.159940   5.160888   5.161898  ...  2.364662  2.364060   

      945.0     950.0     955.0     960.0     965.0     970.0     975.0  \
0  2.491260  2.490473  2.489686  2.488898  2.488111  2.487324  2.486536   
1  5.446694  5.406974  5.367255  5.327535  5.287816  5.248096  5.208376   
2  1.946748  1.941059  1.935370  1.929681  1.923992  1.918303  1.912614   
3  5.228471  5.188967  5.149464  5.109960  5.070456  5.030951  4.991447   
4  2.362651  2.361151  2.359651  2.358151  2.356651  2.355152  2.353652   

      980.0  
0  2.485749  
1  5.168657  
2  1.906924  
3  4.951944  
4  2.352152  

[5 rows x 196 columns]

In [3]:
pres = df.columns[2:].values
lon = df.iloc[:,0].values
lat = df.iloc[:,1].values
X = df.iloc[:,2:].values

In [4]:
np.arange(X.shape[0])

array([   0,    1,    2, ..., 2842, 2843, 2844])

In [5]:
X.shape

(2845, 194)

In [6]:
np.round(np.random.sample(10) * X.shape[1]-1).astype(int)

array([ 35, 167, 132, 151,   2, 187,  84, 182,  37, 171])

In [7]:
y = pd.DataFrame(np.zeros(X.shape))
for i in d.items():
    values = np.round(np.random.sample(10) * (X.shape[1]-1)).astype(int)
    y.iloc[i[0]][values] = 1

NameError: name 'd' is not defined

In [8]:
Xscaled = preprocessing.scale(X)

In [9]:
Xscaled

array([[-0.76209348, -0.75907832, -0.76743843, ..., -0.88347931,
        -0.87946502, -0.87530576],
       [-0.07840178, -0.07283791, -0.06570512, ...,  0.78917083,
         0.78685037,  0.78448412],
       [-1.24751453, -1.24732284, -1.24592457, ..., -1.22822823,
        -1.23082148, -1.23339742],
       ...,
       [-1.6682916 , -1.6732988 , -1.67703665, ..., -1.46777036,
        -1.47287368, -1.47839864],
       [-1.6281307 , -1.65549975, -1.66948367, ..., -1.51577807,
        -1.52053541, -1.52492599],
       [-1.20180085, -1.20071733, -1.19991164, ..., -1.3532636 ,
        -1.35820707, -1.35955599]])

In [68]:
def initialize_model():
    model = models.Sequential()

    model.add(layers.Dense(10, activation='relu', input_dim=194)) # First hidden layer with 5 neurons
    model.add(layers.Dense(7, activation='relu')) # First hidden layer with 5 neurons
    model.add(layers.Dense(194, activation='sigmoid'))
    
    return model

In [69]:
def compile_model(model):
    model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

    return model

In [72]:
es = EarlyStopping(patience=30, restore_best_weights=True)

model = initialize_model()

model = compile_model(model)

history = model.fit(Xscaled, y,
                    validation_split=0.3,
                    epochs=500,
                    batch_size=16, 
                    verbose=1)


Epoch 1/500
125/125 [==============================] - 1s 4ms/step - loss: 0.3570 - accuracy: 0.0000e+00 - val_loss: 0.0592 - val_accuracy: 0.0000e+00
Epoch 2/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0947 - accuracy: 0.0000e+00 - val_loss: 0.0305 - val_accuracy: 0.0000e+00
Epoch 3/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0723 - accuracy: 0.0000e+00 - val_loss: 0.0203 - val_accuracy: 0.0000e+00
Epoch 4/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0555 - accuracy: 0.0000e+00 - val_loss: 0.0154 - val_accuracy: 0.0000e+00
Epoch 5/500
125/125 [==============================] - 0s 4ms/step - loss: 0.0488 - accuracy: 0.0000e+00 - val_loss: 0.0124 - val_accuracy: 0.0000e+00
Epoch 6/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0456 - accuracy: 0.0000e+00 - val_loss: 0.0124 - val_accuracy: 0.0000e+00
Epoch 7/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0440 - accuracy: 

125/125 [==============================] - 0s 3ms/step - loss: 0.0276 - accuracy: 0.0010 - val_loss: 0.0038 - val_accuracy: 0.0000e+00
Epoch 110/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0281 - accuracy: 5.0226e-04 - val_loss: 0.0048 - val_accuracy: 0.0000e+00
Epoch 111/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0276 - accuracy: 0.0010 - val_loss: 0.0053 - val_accuracy: 0.0000e+00
Epoch 112/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0277 - accuracy: 0.0010 - val_loss: 0.0058 - val_accuracy: 0.0000e+00
Epoch 113/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0276 - accuracy: 0.0010 - val_loss: 0.0036 - val_accuracy: 0.0000e+00
Epoch 114/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0277 - accuracy: 5.0226e-04 - val_loss: 0.0038 - val_accuracy: 0.0000e+00
Epoch 115/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0277 - accuracy: 5.0226e-04 - val

125/125 [==============================] - 0s 3ms/step - loss: 0.0269 - accuracy: 0.0030 - val_loss: 0.0037 - val_accuracy: 0.0000e+00
Epoch 219/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0271 - accuracy: 0.0030 - val_loss: 0.0063 - val_accuracy: 0.0000e+00
Epoch 220/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0269 - accuracy: 0.0035 - val_loss: 0.0059 - val_accuracy: 0.0000e+00
Epoch 221/500
125/125 [==============================] - 0s 2ms/step - loss: 0.0269 - accuracy: 0.0025 - val_loss: 0.0041 - val_accuracy: 0.0000e+00
Epoch 222/500
125/125 [==============================] - 0s 2ms/step - loss: 0.0270 - accuracy: 0.0020 - val_loss: 0.0039 - val_accuracy: 0.0000e+00
Epoch 223/500
125/125 [==============================] - 0s 2ms/step - loss: 0.0268 - accuracy: 0.0025 - val_loss: 0.0051 - val_accuracy: 0.0000e+00
Epoch 224/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0268 - accuracy: 0.0035 - val_loss: 0.003

125/125 [==============================] - 0s 2ms/step - loss: 0.0267 - accuracy: 0.0030 - val_loss: 0.0061 - val_accuracy: 0.0000e+00
Epoch 274/500
125/125 [==============================] - 0s 2ms/step - loss: 0.0268 - accuracy: 0.0015 - val_loss: 0.0037 - val_accuracy: 0.0000e+00
Epoch 275/500
125/125 [==============================] - 0s 4ms/step - loss: 0.0267 - accuracy: 0.0030 - val_loss: 0.0034 - val_accuracy: 0.0000e+00
Epoch 276/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0266 - accuracy: 0.0035 - val_loss: 0.0031 - val_accuracy: 0.0000e+00
Epoch 277/500
125/125 [==============================] - 1s 4ms/step - loss: 0.0267 - accuracy: 0.0025 - val_loss: 0.0052 - val_accuracy: 0.0000e+00
Epoch 278/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0267 - accuracy: 0.0040 - val_loss: 0.0037 - val_accuracy: 0.0000e+00
Epoch 279/500
125/125 [==============================] - 1271s 10s/step - loss: 0.0267 - accuracy: 0.0035 - val_loss: 0.

125/125 [==============================] - 0s 2ms/step - loss: 0.0266 - accuracy: 0.0030 - val_loss: 0.0077 - val_accuracy: 0.0000e+00
Epoch 329/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0265 - accuracy: 0.0040 - val_loss: 0.0038 - val_accuracy: 0.0000e+00
Epoch 330/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0264 - accuracy: 0.0045 - val_loss: 0.0034 - val_accuracy: 0.0000e+00
Epoch 331/500
125/125 [==============================] - 0s 3ms/step - loss: 0.0266 - accuracy: 0.0050 - val_loss: 0.0045 - val_accuracy: 0.0000e+00
Epoch 332/500
125/125 [==============================] - 0s 2ms/step - loss: 0.0265 - accuracy: 0.0035 - val_loss: 0.0036 - val_accuracy: 0.0000e+00
Epoch 333/500
125/125 [==============================] - 0s 2ms/step - loss: 0.0266 - accuracy: 0.0030 - val_loss: 0.0047 - val_accuracy: 0.0000e+00
Epoch 334/500
125/125 [==============================] - 0s 2ms/step - loss: 0.0264 - accuracy: 0.0030 - val_loss: 0.004

125/125 [==============================] - 0s 1ms/step - loss: 0.0264 - accuracy: 0.0025 - val_loss: 0.0035 - val_accuracy: 0.0000e+00
Epoch 384/500
125/125 [==============================] - 0s 1ms/step - loss: 0.0265 - accuracy: 0.0030 - val_loss: 0.0041 - val_accuracy: 0.0000e+00
Epoch 385/500
125/125 [==============================] - 0s 1ms/step - loss: 0.0267 - accuracy: 0.0025 - val_loss: 0.0022 - val_accuracy: 0.0000e+00
Epoch 386/500
125/125 [==============================] - 0s 1ms/step - loss: 0.0265 - accuracy: 0.0035 - val_loss: 0.0067 - val_accuracy: 0.0000e+00
Epoch 387/500
125/125 [==============================] - 0s 1ms/step - loss: 0.0264 - accuracy: 0.0030 - val_loss: 0.0046 - val_accuracy: 0.0000e+00
Epoch 388/500
125/125 [==============================] - 0s 1ms/step - loss: 0.0265 - accuracy: 0.0030 - val_loss: 0.0044 - val_accuracy: 0.0000e+00
Epoch 389/500
125/125 [==============================] - 0s 1ms/step - loss: 0.0264 - accuracy: 0.0035 - val_loss: 0.004

125/125 [==============================] - 0s 1ms/step - loss: 0.0263 - accuracy: 0.0025 - val_loss: 0.0048 - val_accuracy: 0.0000e+00
Epoch 439/500
125/125 [==============================] - 0s 1ms/step - loss: 0.0264 - accuracy: 0.0030 - val_loss: 0.0051 - val_accuracy: 0.0000e+00
Epoch 440/500
125/125 [==============================] - 0s 1ms/step - loss: 0.0263 - accuracy: 0.0020 - val_loss: 0.0043 - val_accuracy: 0.0000e+00
Epoch 441/500
125/125 [==============================] - 0s 2ms/step - loss: 0.0263 - accuracy: 0.0025 - val_loss: 0.0069 - val_accuracy: 0.0000e+00
Epoch 442/500
125/125 [==============================] - 0s 1ms/step - loss: 0.0264 - accuracy: 0.0025 - val_loss: 0.0045 - val_accuracy: 0.0000e+00
Epoch 443/500
125/125 [==============================] - 0s 1ms/step - loss: 0.0262 - accuracy: 0.0025 - val_loss: 0.0051 - val_accuracy: 0.0000e+00
Epoch 444/500
125/125 [==============================] - 0s 1ms/step - loss: 0.0264 - accuracy: 0.0025 - val_loss: 0.004

125/125 [==============================] - 0s 1ms/step - loss: 0.0263 - accuracy: 0.0020 - val_loss: 0.0033 - val_accuracy: 0.0000e+00
Epoch 494/500
125/125 [==============================] - 0s 1ms/step - loss: 0.0264 - accuracy: 0.0020 - val_loss: 0.0045 - val_accuracy: 0.0000e+00
Epoch 495/500
125/125 [==============================] - 0s 1ms/step - loss: 0.0263 - accuracy: 0.0025 - val_loss: 0.0044 - val_accuracy: 0.0000e+00
Epoch 496/500
125/125 [==============================] - 0s 1ms/step - loss: 0.0262 - accuracy: 0.0030 - val_loss: 0.0048 - val_accuracy: 0.0000e+00
Epoch 497/500
125/125 [==============================] - 0s 981us/step - loss: 0.0261 - accuracy: 0.0025 - val_loss: 0.0043 - val_accuracy: 0.0000e+00
Epoch 498/500
125/125 [==============================] - 0s 1ms/step - loss: 0.0262 - accuracy: 0.0025 - val_loss: 0.0038 - val_accuracy: 0.0000e+00
Epoch 499/500
125/125 [==============================] - 0s 1ms/step - loss: 0.0263 - accuracy: 0.0025 - val_loss: 0.0

In [73]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import interpolate
x = np.arange(0, 10)
y = np.exp(-x/3.0)
f = interpolate.interp1d(x, y)

In [74]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
y

array([1.        , 0.71653131, 0.51341712, 0.36787944, 0.26359714,
       0.1888756 , 0.13533528, 0.09697197, 0.06948345, 0.04978707])

In [76]:
f

In [78]:
xnew


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9])

In [77]:
xnew = np.arange(0, 9, 0.1)
ynew = f(xnew)
ynew

array([1.        , 0.97165313, 0.94330626, 0.91495939, 0.88661252,
       0.85826566, 0.82991879, 0.80157192, 0.77322505, 0.74487818,
       0.71653131, 0.69621989, 0.67590847, 0.65559705, 0.63528563,
       0.61497421, 0.5946628 , 0.57435138, 0.55403996, 0.53372854,
       0.51341712, 0.49886335, 0.48430958, 0.46975582, 0.45520205,
       0.44064828, 0.42609451, 0.41154074, 0.39698698, 0.38243321,
       0.36787944, 0.35745121, 0.34702298, 0.33659475, 0.32616652,
       0.31573829, 0.30531006, 0.29488183, 0.2844536 , 0.27402537,
       0.26359714, 0.25612498, 0.24865283, 0.24118068, 0.23370852,
       0.22623637, 0.21876422, 0.21129206, 0.20381991, 0.19634776,
       0.1888756 , 0.18352157, 0.17816754, 0.17281351, 0.16745947,
       0.16210544, 0.15675141, 0.15139738, 0.14604335, 0.14068932,
       0.13533528, 0.13149895, 0.12766262, 0.12382629, 0.11998996,
       0.11615363, 0.11231729, 0.10848096, 0.10464463, 0.1008083 ,
       0.09697197, 0.09422312, 0.09147426, 0.08872541, 0.08597